### PR TITLE
Psalm integration

### LINKED ISSUE #7: Psalm integration
### Feature Request

|    Q        |   A
|------------ | ------
| QA    | yes

#### Summary

As decided during the [Technical-Steering-Committee Meeting on August 3rd, 2020](https://github.com/laminas/technical-steering-committee/blob/main/meetings/minutes/2020-08-03-TSC-Minutes.md#vote-on-static-analysis-tooling), Laminas wants to implement [vimeo/psalm](https://github.com/vimeo/psalm) in all packages.

Implementing psalm is quite easy.

#### Required
- [ ] Create a `psalm.xml` in the project root
- [ ] Copy and paste the contents from this [psalm.xml.dist](https://github.com/mezzio/repo-template/blob/6124090610ef1c6d6b0c80a063cafacc3ec68f38/psalm.xml.dist)
- [ ] Run `$ composer require --dev vimeo/psalm`
- [ ] Run `$ vendor/bin/psalm --set-baseline=psalm-baseline.xml`
- [ ] Add a composer script `static-analysis` with the command `psalm --shepherd --stats`
- [ ] Add a new line to `script:` in `.travis.yml`: `- if [[ $TEST_COVERAGE == 'true' ]]; then composer static-analysis ; fi`
- [ ] Remove phpstan from the project (`phpstan.neon.dist`, `.travis.yml` entry, `composer.json` `require-dev` and `scripts`)

##### Optional
- [ ] Fix as many psalm errors as possible.

### PR DESCRIPTION
**Pull request by ghostwriter**
|    Q          |   A
|-------------- | ------
| QA            | yes

### Description

- [x] Create psalm.xml
- [x] Require vimeo/psalm
- [x] Create psalm-baseline.xml
- [x] Require psalm/plugin-phpunit
- [x] Add static-analysis composer script
- [x] Add GHA CI workflow 
- [x] Update composer.lock

Resolves #7

### CODE REVIEW

**Comment by froschdesign** [comment]
@ghostwriter 
> Add GHA CI workflow

Is this a backport from branch 1.6.x (#12)?

**Comment by boesing** [comment]
> Is this a backport from branch 1.6.x (#12)?

Seems so, I'd say lets retarget this to 1.6.x.
This actually adds no further value and thus, it can stay in the 1.6.x branch until we add new features.

Please rebase this PR against 1.6.x - after this, I'm happy to merge.

**Comment by ghostwriter** [comment]
@froschdesign yes, at least that was my intention.

Also, I'm not sure if that pr was meant to target `1.5.x` instead of `1.6.x`.

Is `1.5.x` NOT the current release branch?

@boesing How did you change the base branch? 

`git rebase --onto 1.6.x 1.5.x ghostwriter:psalm-integration`?

**Comment by boesing** [comment]
I just changed the target branch on github. Rebase should be done in your branch.

Should be something like `git rebase upstream/1.6.x` while in your branch.
If you dont have the upstream remote, you should add it:

```
git remote add upstream git@github.com:laminas/laminas-config-aggregator-parameters.git
git fetch upstream
git rebase upstream/1.6.x
```

**Comment by ghostwriter** [comment]
> I just changed the target branch on github.

Oh! Thanks, I thought a git command rendered the "boesing changed the base branch from `1.5.x` to `1.6.x`" message above.

**Review by boesing — APPROVED** [review]
LGTM

**Comment by boesing** [comment]
Thanks, @ghostwriter.
I'll keep this unreleased until we have any code additions but anyways, thanks for this PR.

**Pull request merged**
